import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { LangProvider } from "@/lib/langContext";
import { ThemeProvider } from "@/lib/themeContext";
import "./globals.css";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin", "cyrillic"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.variable} h-full antialiased`}>
      <body
        className={`${nunito.className} min-h-full flex flex-col transition-colors duration-200`}
      >
        <ThemeProvider>
          <LangProvider>{children}</LangProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
